### ISSUE TITLE
Incorect download URL for Mac OS

### ISSUE THREAD

**Issue by ali-baykal** [torakiki/pdfsam-visual-public#1]
Hi,

at https://pdfsam.org/download-pdfsam-visual/ the Apple disk image points to https://github.com/torakiki/pdfsam-visual-public/releases/download/v5.0.0/pdfsam-visual_5.0.0.dmg, which does not work . On the releases page it is https://github.com/torakiki/pdfsam-visual-public/releases/download/v.5.0.0/pdfsam-visual_5.0.0.dmg .

The difference appears to be in v5.0.0 vs v.5.0.0 (the working url has a dot after v).

Thanks for PDFSam,
have a nice day,
Ali

**Comment by torakiki** [comment]
Thanks!
